### ISSUE TITLE
关于读取yaml文件时出错的问题

### ISSUE THREAD

**Issue by gbdpf** [baidu/boteye_driver#5]
您好，我在运行depth_demo时，会出现段错误，用gdb定位在yaml文件读取：

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe363b700 (LWP 19352)]
YAML::detail::node::get<std::string> (this=0x7fffd41c71d0, key="DeviceId", pMemory=
    std::shared_ptr<YAML::detail::memory_holder> (use count 7, weak count 0) = {...})
    at /usr/local/include/yaml-cpp/node/detail/node_ref.h:25
25	  NodeType::value type() const { return m_pData->type(); }
```

我的yaml文件如下：
```
DeviceId: ""
SensorType: UNKNOWN
Imu:
  accel_TK:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]
  accel_bias: [0, 0, 0]
  gyro_TK:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]
  gyro_bias: [0, 0, 0]
  accel_noise_var: [0.0016, 0.0016, 0.0016]
  angv_noise_var: [0.0001, 0.0001, 0.0001]
  D_T_I:
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
```
　请问一下这个是yaml文件的问题，还是别的问题？
